# Generated by Django 3.1.7 on 2021-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_bio_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekKey', models.CharField(max_length=50)),
                ('weekDesc', models.CharField(max_length=100)),
            ],
        ),
    ]
