# Generated by Django 3.1.7 on 2021-04-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_week_weekdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todayDesc', models.CharField(max_length=100)),
                ('todayDone', models.BooleanField(default=False)),
                ('todayKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.key')),
            ],
        ),
    ]
